// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportPulse.Data.Context;

#nullable disable

namespace SupportPulse.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720145337_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ChatUniqId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LockedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SupportCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatStatusId");

                    b.HasIndex("LockedByAdminId");

                    b.HasIndex("SupportCategoryId");

                    b.HasIndex("ChatUniqId", "CreatorId")
                        .HasDatabaseName("IX_Chats_ChatUniqId_CreatorId");

                    b.HasIndex("CreatorId", "CreatedTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Chats_CreatorId_CreatedTime");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatorId", "CreatedTime"), new[] { "ChatUniqId", "Subject", "ChatStatusId", "SupportCategoryId" });

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.ChatStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChatStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "گفتگو تکمیل شد."
                        },
                        new
                        {
                            Id = 2,
                            Name = "درحال پاسخگویی"
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<int>("MessageContentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MessageContentId")
                        .IsUnique();

                    b.HasIndex("SenderId");

                    b.HasIndex("ChatId", "Time")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Messages_ChatId_Time_Desc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ChatId", "Time"), new[] { "MessageContentId" });

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.MessageContent.AttachFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MessageContentId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SavedPath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("MessageContentId");

                    b.HasIndex("SavedPath")
                        .HasDatabaseName("IX_AttachFiles_SavedPath");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SavedPath"), new[] { "MessageContentId" });

                    b.ToTable("AttachFiles");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageTypeId");

                    b.ToTable("MessageContents");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MessageTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "متن"
                        },
                        new
                        {
                            Id = 2,
                            Name = "فایل"
                        },
                        new
                        {
                            Id = 3,
                            Name = "متن و فایل"
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Ban.UserBanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BanExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BannedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BannedByAdminId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBanHistories");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Notification.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.RefreshToken.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Role.Permission.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Name = "داشبورد پنل ادمین"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            Name = "لیست نقش‌ها"
                        },
                        new
                        {
                            Id = 3,
                            Category = "General",
                            Name = "افزودن نقش"
                        },
                        new
                        {
                            Id = 4,
                            Category = "General",
                            Name = "ویرایش نقش"
                        },
                        new
                        {
                            Id = 5,
                            Category = "General",
                            Name = "حذف نقش"
                        },
                        new
                        {
                            Id = 6,
                            Category = "General",
                            Name = "لیست کاربران"
                        },
                        new
                        {
                            Id = 7,
                            Category = "General",
                            Name = "مسدود کردن کاربر"
                        },
                        new
                        {
                            Id = 8,
                            Category = "General",
                            Name = "رفع مسدودیت کاربر"
                        },
                        new
                        {
                            Id = 9,
                            Category = "General",
                            Name = "تغییر مدت مسدودیت"
                        },
                        new
                        {
                            Id = 10,
                            Category = "General",
                            Name = "مشاهده تاریخچه مسدودیت"
                        },
                        new
                        {
                            Id = 11,
                            Category = "General",
                            Name = "لیست واحدهای پشتیبانی"
                        },
                        new
                        {
                            Id = 12,
                            Category = "General",
                            Name = "افزودن واحد پشتیبانی"
                        },
                        new
                        {
                            Id = 13,
                            Category = "General",
                            Name = "ویرایش واحد پشتیبانی"
                        },
                        new
                        {
                            Id = 14,
                            Category = "General",
                            Name = "مشاهده لیست چت‌ها"
                        },
                        new
                        {
                            Id = 15,
                            Category = "General",
                            Name = "مشاهده جزئیات چت"
                        },
                        new
                        {
                            Id = 16,
                            Category = "General",
                            Name = "قفل کردن چت"
                        },
                        new
                        {
                            Id = 17,
                            Category = "General",
                            Name = "آزادسازی چت"
                        },
                        new
                        {
                            Id = 18,
                            Category = "General",
                            Name = "پایان دادن به چت"
                        },
                        new
                        {
                            Id = 19,
                            Category = "General",
                            Name = "ارسال پیام در چت"
                        },
                        new
                        {
                            Id = 20,
                            Category = "General",
                            Name = "تخصیص نقش به کاربر"
                        },
                        new
                        {
                            Id = 21,
                            Category = "General",
                            Name = "تخصیص واحد پشتیبانی به کاربر"
                        },
                        new
                        {
                            Id = 101,
                            Category = "Notification",
                            Name = "اعلان آزادسازی چت"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Notification",
                            Name = "اعلان قفل شدن چت"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Notification",
                            Name = "اعلان پایان چت"
                        },
                        new
                        {
                            Id = 104,
                            Category = "Notification",
                            Name = "اعلان مسدود شدن کاربر"
                        },
                        new
                        {
                            Id = 105,
                            Category = "Notification",
                            Name = "اعلان رفع مسدودی کاربر"
                        },
                        new
                        {
                            Id = 106,
                            Category = "Notification",
                            Name = "اعلان تغییر مدت مسدودی"
                        },
                        new
                        {
                            Id = 107,
                            Category = "Notification",
                            Name = "اعلان ایجاد نقش"
                        },
                        new
                        {
                            Id = 108,
                            Category = "Notification",
                            Name = "اعلان ویرایش نقش"
                        },
                        new
                        {
                            Id = 109,
                            Category = "Notification",
                            Name = "اعلان حذف نقش"
                        },
                        new
                        {
                            Id = 110,
                            Category = "Notification",
                            Name = "اعلان ایجاد واحد پشتیبانی"
                        },
                        new
                        {
                            Id = 111,
                            Category = "Notification",
                            Name = "اعلان ویرایش واحد پشتیبانی"
                        },
                        new
                        {
                            Id = 112,
                            Category = "Notification",
                            Name = "اعلان آزادسازی خودکار چت"
                        },
                        new
                        {
                            Id = 113,
                            Category = "Notification",
                            Name = "اعلان تغییر نقش‌های کاربر"
                        },
                        new
                        {
                            Id = 114,
                            Category = "Notification",
                            Name = "اعلان تغییر واحدهای پشتیبانی کاربر"
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Role.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "مدیر کل"
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Role.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 101
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 102
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 103
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 104
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 105
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 106
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 107
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 108
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 109
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 110
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 111
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 112
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 113
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 114
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.SupportCategory.SupportCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SupportCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "توضیحاتی مختصر درمورد واحد فنی",
                            IconKey = "technical",
                            IsActive = true,
                            Name = "واحد فنی"
                        },
                        new
                        {
                            Id = 2,
                            Details = "توضیحاتی مختصر درمورد واحد فروش",
                            IconKey = "sales",
                            IsActive = true,
                            Name = "واحد فروش"
                        },
                        new
                        {
                            Id = 3,
                            Details = "توضیحاتی مختصر درمورد واحد مدیریت",
                            IconKey = "management",
                            IsActive = true,
                            Name = "واحد مدیریت"
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.SupportCategory.UserSupportCategory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SupportCategoryId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SupportCategoryId");

                    b.HasIndex("SupportCategoryId");

                    b.HasIndex("UserId", "SupportCategoryId")
                        .HasDatabaseName("IX_UserSupportCategories_UserId_SupportCategoryId");

                    b.ToTable("UserSupportCategories");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            SupportCategoryId = 1
                        },
                        new
                        {
                            UserId = 1,
                            SupportCategoryId = 2
                        },
                        new
                        {
                            UserId = 1,
                            SupportCategoryId = 3
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BanExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("IsBan")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "ادمین",
                            IsBan = false,
                            LastName = "اصلی",
                            Password = "Argon2id$mem=65536;iter=3;par=4$ABX4d3wa6rdwM4SsxCjB0A==$dDUptPckroNuD0JtMyHqjV+ZMifgKTtHHxcvJN61cmc=",
                            SecurityStamp = "68b6608745fc42f6b03bfa0ad68ac339d5ef90fbeee549a7833a1c985aae7d91",
                            UserName = "manager"
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Chat", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.Chat.ChatStatus", "ChatStatus")
                        .WithMany("Chats")
                        .HasForeignKey("ChatStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportPulse.Data.Entities.User.User", "Creator")
                        .WithMany("Chats")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SupportPulse.Data.Entities.User.User", "LockedByAdmin")
                        .WithMany("LockedChats")
                        .HasForeignKey("LockedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SupportPulse.Data.Entities.User.SupportCategory.SupportCategory", "SupportCategory")
                        .WithMany("Chats")
                        .HasForeignKey("SupportCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatStatus");

                    b.Navigation("Creator");

                    b.Navigation("LockedByAdmin");

                    b.Navigation("SupportCategory");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.Message", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.Chat.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageContent", "MessageContent")
                        .WithOne("Message")
                        .HasForeignKey("SupportPulse.Data.Entities.Chat.Message.Message", "MessageContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportPulse.Data.Entities.User.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("MessageContent");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.MessageContent.AttachFile", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageContent", "MessageContent")
                        .WithMany("AttachFiles")
                        .HasForeignKey("MessageContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageContent");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageContent", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageType", "MessageType")
                        .WithMany("Messages")
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageType");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Ban.UserBanHistory", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.User.User", "Admin")
                        .WithMany("BansIssued")
                        .HasForeignKey("BannedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SupportPulse.Data.Entities.User.User", "User")
                        .WithMany("BanHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Notification.AdminNotification", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.User.User", "AdminUser")
                        .WithMany("AdminNotifications")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.RefreshToken.RefreshToken", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.User.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Role.RolePermission", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.User.Role.Permission.Permission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportPulse.Data.Entities.User.Role.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.SupportCategory.UserSupportCategory", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.User.SupportCategory.SupportCategory", "SupportCategory")
                        .WithMany("Users")
                        .HasForeignKey("SupportCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportPulse.Data.Entities.User.User", "User")
                        .WithMany("SupportCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.UserRole", b =>
                {
                    b.HasOne("SupportPulse.Data.Entities.User.Role.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportPulse.Data.Entities.User.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.ChatStatus", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageContent", b =>
                {
                    b.Navigation("AttachFiles");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.Chat.Message.MessageContent.MessageType", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Role.Permission.Permission", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.Role.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.SupportCategory.SupportCategory", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SupportPulse.Data.Entities.User.User", b =>
                {
                    b.Navigation("AdminNotifications");

                    b.Navigation("BanHistories");

                    b.Navigation("BansIssued");

                    b.Navigation("Chats");

                    b.Navigation("LockedChats");

                    b.Navigation("Messages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");

                    b.Navigation("SupportCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
